name: Build Cli-Boy (cross-platform, debug)

on:
  push:
  pull_request:

jobs:
  get-version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - id: version
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{ github.ref_name }}"
          echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT

  build:
    name: Build (${{ matrix.artifact-name }})
    needs: get-version
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            artifact-name: cli-boy-linux-x86_64
            package-ext: tar.gz
            content-type: application/gzip

          - os: ubuntu-24.04-arm
            arch: aarch64
            artifact-name: cli-boy-linux-aarch64
            package-ext: tar.gz
            content-type: application/gzip

          - os: macos-15-intel
            arch: x86_64
            artifact-name: cli-boy-macos-x86_64
            package-ext: tar.gz
            content-type: application/gzip

          - os: macos-latest
            arch: aarch64
            artifact-name: cli-boy-macos-aarch64
            package-ext: tar.gz
            content-type: application/gzip

          - os: windows-latest
            arch: x86_64
            artifact-name: cli-boy-windows-x86_64
            package-ext: zip
            content-type: application/x-zip-compressed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # Dependencies
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && sudo apt-get purge firefox -y
          sudo apt-get install -y build-essential pkg-config make

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install pkg-config make

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            zip
            patch
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make

      # Build
      - name: Build project (Linux / macOS)
        if: runner.os != 'Windows'
        run: make all DEBUG=1

      - name: Build project (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: make all DEBUG=1

      # Packaging
      - name: Package (Linux / macOS)
        if: runner.os != 'Windows'
        run: |
          mv ./build/debug/cliboy .
          tar -zcf ${{ matrix.artifact-name }}.tar.gz cliboy assets/

      - name: Package (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          mkdir -p build-zip/
          mv ./build/debug/cliboy.exe assets/ ./build-zip/
          cd ./build-zip/
          ldd ./cliboy.exe | grep -i mingw | awk '{print $3}' | xargs -i cp {} ./
          zip -r ../${{ matrix.artifact-name }}.zip *

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          if-no-files-found: error
          path: ./${{ matrix.artifact-name }}.${{ matrix.package-ext }}
